name: Build SafeHER APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout SafeHER
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install buildozer
          python -m pip install "cython<3.2"

           - name: Set Android SDK
        run: |
          echo "ANDROIDSDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROIDSDK=$ANDROID_HOME"
          ls -la "$ANDROID_HOME"

      - name: Build SafeHER APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SafeHER-APK
          path: bin/*.apk
